export const BUTTON_CLICK = 'BUTTON_CLICK';
export const BUTTON_CLICK_SUCCESS = 'BUTTON_CLICK_SUCCESS';
export const BUTTON_CLICK_FAILURE = 'BUTTON_CLICK_FAILURE';
export const BUTTON_CLICK_REQUEST = 'BUTTON_CLICK_REQUEST';

// Auth
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
